[package]
name = "gfalace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1.9.1"
clap = { version = "4.5.2", features = ["derive"] }
handlegraph = { git = "https://github.com/chfi/rs-handlegraph", branch = "master" }
gfa = "0.10.1"
